require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/media_attachments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MediaAttachment. As you add validations to MediaAttachment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MediaAttachment.create! valid_attributes
      get media_attachments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      media_attachment = MediaAttachment.create! valid_attributes
      get media_attachment_url(media_attachment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_media_attachment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      media_attachment = MediaAttachment.create! valid_attributes
      get edit_media_attachment_url(media_attachment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MediaAttachment" do
        expect {
          post media_attachments_url, params: { media_attachment: valid_attributes }
        }.to change(MediaAttachment, :count).by(1)
      end

      it "redirects to the created media_attachment" do
        post media_attachments_url, params: { media_attachment: valid_attributes }
        expect(response).to redirect_to(media_attachment_url(MediaAttachment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MediaAttachment" do
        expect {
          post media_attachments_url, params: { media_attachment: invalid_attributes }
        }.to change(MediaAttachment, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post media_attachments_url, params: { media_attachment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested media_attachment" do
        media_attachment = MediaAttachment.create! valid_attributes
        patch media_attachment_url(media_attachment), params: { media_attachment: new_attributes }
        media_attachment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the media_attachment" do
        media_attachment = MediaAttachment.create! valid_attributes
        patch media_attachment_url(media_attachment), params: { media_attachment: new_attributes }
        media_attachment.reload
        expect(response).to redirect_to(media_attachment_url(media_attachment))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        media_attachment = MediaAttachment.create! valid_attributes
        patch media_attachment_url(media_attachment), params: { media_attachment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested media_attachment" do
      media_attachment = MediaAttachment.create! valid_attributes
      expect {
        delete media_attachment_url(media_attachment)
      }.to change(MediaAttachment, :count).by(-1)
    end

    it "redirects to the media_attachments list" do
      media_attachment = MediaAttachment.create! valid_attributes
      delete media_attachment_url(media_attachment)
      expect(response).to redirect_to(media_attachments_url)
    end
  end
end
